title: Enhanced GitHub Pages Demo
description: A Jekyll-powered GitHub Pages site with interactive bash commands
baseurl: ""
url: "https://your-username.github.io"

# Theme
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - about.md
  - commands.md

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/